name = "Madeline"
uuid = "4db2d6d9-0925-4ef8-b567-cc767be9a2ec"
license = "MIT"
version = "0.0.1"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]

[deps]
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[sources]
CliqueTrees = {path = "../CliqueTrees.jl"}

[compat]
CliqueTrees = "1"
CommonSolve = "0.2.6"
LinearAlgebra = "1"
MathOptInterface = "1.51.0"
OffsetArrays = "1.17.0"
Printf = "1"
SparseArrays = "1"
julia = "1.10"
